from setuptools import setup, find_packages

VERSION = open("quarchive/VERSION").read().strip()

setup(
    name="quarchive",
    version=VERSION,
    packages=find_packages(exclude=["tests.*", "tests"]),
    include_package_data=True,
    zip_safe=False,
    install_requires=[
        "Flask-Babel~=2.0.0",
        "Pillow~=8.3.2",
        "PyYaml~=5.4.1",
        "argon2_cffi~=20.1.0",
        "attrs~=20.3.0",
        "babel~=2.9.0",
        "bcrypt~=3.2.0",
        "boto3~=1.11.0",
        "click~=7.1.2",
        "commonmark~=0.9.1",
        "flask-cors~=3.0.10",
        "flask-sqlalchemy~=2.5.1",
        "flask==1.1.1",
        "kombu==5.0.2",
        "lxml~=4.6.3",
        "missive==0.8.1",
        "passlib~=1.7.4",
        "psycopg2==2.8.6",
        "pyappcache[memcache]==0.2",
        "pyhash==0.9.3",
        "python-dateutil~=2.8.1",
        "python-magic~=0.4.22",
        "pytz",
        "requests~=2.25.0",
        "sqlalchemy==1.3.22",
        "systemd-python==234",
        "werkzeug~=1.0.1",
    ],
    extras_require={
        "tests": [
            "alembic~=1.3.1",
            "cssselect~=1.1.0",
            "freezegun~=0.3.12",
            "hypothesis~=4.50.6",
            "moto[s3]~=1.3.16",
            "pytest-env~=0.6.2",
            "pytest-flask~=1.1.0",
            "pytest-xdist~=2.2.0",
            "pytest~=6.2.1",
            "responses~=0.10.9",
        ],
        "dev": [
            "alembic~=1.3.1",
            "black~=19.10b0",
            "bpython~=0.18",
            "mypy==0.790",
            "sqlalchemy-stubs~=0.4",
            "wheel~=0.33.6",
        ],
    },
    entry_points={
        "console_scripts": [
            "quarchive=quarchive.cli:quarchive_cli",
            "qm-pinboard-import=quarchive.pinboard:pinboard_import",
            "quarchive-bg-worker=quarchive.bg_worker:bg_worker",
            "quarchive-get-crawl-body=quarchive.cli:get_crawl_body",
            "quarchive-reindex-url=quarchive.cli:reindex_url",
            "quarchive-reindex-bookmarks=quarchive.cli:reindex_bookmarks",
            "quarchive-url-recheck=quarchive:url_recheck",
        ]
    },
)
