#!/usr/bin/env python3

"""Generate extension manifest files for different browsers.

Chrome and Firefox have slightly different expectations about what should be in these files.

"""

import argparse
import json
from sys import stdout


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("browser", type=str, choices=["chrome", "firefox"])
    parser.add_argument("version", type=str)
    args = parser.parse_args()

    manifest = {
        "manifest_version": 2,
        "name": "Quarchive",
        "version": args.version,
        "permissions": [
            "bookmarks",
            "storage",
            "unlimitedStorage"
        ],
        "background": {
            "page": "background.html"
        },
        "options_ui": {
            "page": "options.html",
        }
    }

    if args.browser == "firefox":
        manifest["browser_specific_settings"] = {
            "gecko": {
                "id": "{ee416e00-528a-4b7b-a0d2-98bae198d30c}",
                "update_url": (
                    "https://quarchive.com/extension/gecko/updates.json"
                )
            }
        }
        manifest["options_ui"]["browser_style"] = True
    else:
        manifest["options_ui"]["chrome_style"] = True

    json.dump(manifest, stdout, indent=4)


if __name__ == "__main__":
    main()
